import test from "node:test";
import assert from "node:assert/strict";
import vm from "node:vm";
import {readFile} from "node:fs/promises";
import {webcrypto} from "node:crypto";

test("content script requires post-click employer confirmation and rejects validation errors",async()=>{
  const source=await readFile(new URL("../executor/chrome-extension/content-script.js",import.meta.url),"utf8");let listener,text="Thank you for applying. Your application has been received.";
  const context={crypto:webcrypto,TextEncoder,URL,location:{href:"https://employer.example/application/confirmation"},document:{body:{get innerText(){return text}},querySelectorAll:()=>[]},chrome:{runtime:{onMessage:{addListener:value=>{listener=value}}}}};vm.runInNewContext(source,context);
  const call=message=>new Promise(resolve=>listener(message,{},resolve));
  const accepted=await call({type:"TN_OBSERVE_SUBMISSION_CONFIRMATION",before_url:"https://employer.example/apply"});assert.equal(accepted.ok,true);assert.equal(accepted.value.confirmation_url,"https://employer.example/application/confirmation");assert.match(accepted.value.detail_hash,/^[a-f0-9]{64}$/);
  const unchangedFingerprint=[...new Uint8Array(await webcrypto.subtle.digest("SHA-256",new TextEncoder().encode("Thank you for applying")))].map(x=>x.toString(16).padStart(2,"0")).join("");const unchanged=await call({type:"TN_OBSERVE_SUBMISSION_CONFIRMATION",before_url:context.location.href,before_confirmation_fingerprint:unchangedFingerprint});assert.equal(unchanged.value,null);context.location.href="https://employer.example/apply?attempt=1";const unrelatedUrlChange=await call({type:"TN_OBSERVE_SUBMISSION_CONFIRMATION",before_url:"https://employer.example/apply",before_confirmation_fingerprint:unchangedFingerprint});assert.equal(unrelatedUrlChange.value,null);context.location.href="https://employer.example/application/confirmation";
  text="Please correct the required field. Thank you for applying.";const rejected=await call({type:"TN_OBSERVE_SUBMISSION_CONFIRMATION",before_url:"https://employer.example/apply"});assert.equal(rejected.ok,true);assert.equal(rejected.value,null);
});

test("checked-in manifest stages durably and local activeTab flow inspects the clicked employer tab",async()=>{
  const [manifest,source]=await Promise.all([readFile(new URL("../executor/chrome-extension/manifest.json",import.meta.url),"utf8"),readFile(new URL("../executor/chrome-extension/service-worker.js",import.meta.url),"utf8")]);const parsed=JSON.parse(manifest);assert.deepEqual(parsed.content_scripts,[{matches:["https://truenorth.justsignal.company/*"],js:["dashboard-bridge.js"],run_at:"document_start"}]);let internal;
  const permissions=[],removed=[],session={},created=[],injected=[];let action,alarmListener;const context={URL,Date,structuredClone,fetch:async request=>Response.json({lease_token:"lease",id:"queue-123"}),Response,setTimeout,clearTimeout,chrome:{runtime:{sendNativeMessage(host,message,callback){callback(message.type==="status"?{ok:true,paired:true,device_id:"executor_device_"+"a".repeat(32)}:{timestamp:"2026-10-09T00:00:00Z",nonce:"a".repeat(32),signature:"signed"})},lastError:null,onMessage:{addListener:value=>{internal=value}}},storage:{session:{get:async key=>({[key]:session[key]}),set:async value=>Object.assign(session,value)}},alarms:{create:async()=>true,clear:async()=>true,onAlarm:{addListener:value=>{alarmListener=value}}},tabs:{sendMessage(tabId,message,callback){callback({ok:true,value:{destination_url:"https://employer.example/apply",form_state_hash:"b".repeat(64)}})},create:async value=>(created.push(value),{id:99})},scripting:{executeScript:async value=>injected.push(value.target.tabId)},permissions:{request:async value=>(permissions.push(value),true),remove:async value=>(removed.push(value),true)},action:{onClicked:{addListener:value=>{action=value}}}}};vm.runInNewContext(source,context);
  let response;await new Promise(resolve=>internal({type:"TN_STAGE_EXECUTION_HANDOFF",handoff:{kind:"true_north_browser_execution_handoff",queue_id:"queue-123",destination_url:"https://employer.example/apply"}},{origin:"https://truenorth.justsignal.company",url:"https://truenorth.justsignal.company/"},value=>{response=value;resolve()}));assert.equal(response.ok,true);assert.equal(response.status,"staged_waiting_for_local_extension_gesture");assert.equal(session.executor_state.staged.queue_id,"queue-123");
  await new Promise(resolve=>internal({type:"TN_GRANT_EXACT_ORIGIN",origin:"https://employer.example"},{origin:"https://truenorth.justsignal.company",url:"https://truenorth.justsignal.company/"},value=>{response=value;resolve()}));assert.equal(response.origin_pattern,"https://employer.example/*");assert.equal(permissions[0].origins[0],"https://employer.example/*");
  await action({id:42,url:"https://employer.example/apply"});assert.deepEqual(injected,[42]);assert.equal(created.length,1);assert.match(created[0].url,/^https:\/\/truenorth\.justsignal\.company\/\?executor_authorize=/);assert.equal(session.executor_state.executionContext.tab_id,42);
  response=undefined;internal({type:"TN_STAGE_EXECUTION_HANDOFF",handoff:{kind:"true_north_browser_execution_handoff",queue_id:"queue-456",destination_url:"https://employer.example/apply"}},{origin:"https://evil.example",url:"https://evil.example/"},value=>{response=value});assert.equal(response,undefined);
  await alarmListener({name:"true-north-exact-origin-expiry"});await new Promise(resolve=>setTimeout(resolve,0));assert.equal(removed[0].origins[0],"https://employer.example/*");assert.equal(session.executor_state.temporaryOriginGrant,null);
});
