import test from "node:test";import assert from "node:assert/strict";import{webcrypto}from"node:crypto";import{OAuthCoordinator,seal,open,CALLBACK_URL,SCOPE}from"../oauth-broker.js";
globalThis.crypto||=webcrypto;globalThis.btoa||=(v=>Buffer.from(v,"binary").toString("base64"));globalThis.atob||=(v=>Buffer.from(v,"base64").toString("binary"));
class Storage{constructor(){this.m=new Map()}async put(k,v){this.m.set(k,v)}async get(k){return this.m.get(k)}async delete(k){this.m.delete(k)}async transaction(fn){return fn(this)}}
const make=()=>{const storage=new Storage(),env={OAUTH_CLIENT_ID:"public-client-id",OAUTH_CLIENT_SECRET:"fixture-secret",TOKEN_ENCRYPTION_KEY:Buffer.alloc(32,7).toString("base64url")};return{storage,env,coordinator:new OAuthCoordinator({storage},env)}};
const call=(c,path,body)=>c.fetch(new Request(`https://core.invalid${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}));
test("state is session-bound, PKCE-enabled, exact-scope and callback pinned",async()=>{const{coordinator:c,storage}=make(),b=await(await call(c,"/begin",{session_binding:"session-hash"})).json(),u=new URL(b.authorization_url),state=u.searchParams.get("state"),flow=await storage.get(`flow:${state}`);assert.equal(flow.session_binding,"session-hash");assert.ok(b.browser_nonce);assert.equal(u.searchParams.get("scope"),SCOPE);assert.equal(u.searchParams.get("redirect_uri"),CALLBACK_URL);assert.equal(u.searchParams.get("code_challenge_method"),"S256")});
test("AES-GCM uses distinct nonces and hides plaintext",async()=>{const{env}=make(),a=await seal(env,{refresh_token:"secret"}),b=await seal(env,{refresh_token:"secret"});assert.notEqual(a.split(".")[0],b.split(".")[0]);assert.notEqual(a,b);assert.equal(a.includes("secret"),false);assert.equal((await open(env,a)).refresh_token,"secret")});
test("status proves live read-only access and never exposes credentials",async()=>{const{coordinator:c,storage,env}=make();assert.deepEqual(await(await call(c,"/status",{})).json(),{connected:false,account_email:null,scopes:[],status:"disconnected",live_access_verified:false});await storage.put("grant",await seal(env,{refresh_token:"never-expose-this",mailbox:"ctiberius@gmail.com",scope:SCOPE,status:"active"}));const old=globalThis.fetch;globalThis.fetch=async u=>String(u).includes("/profile")?Response.json({emailAddress:"ctiberius@gmail.com"}):Response.json({access_token:"never-expose-access",expires_in:3600});try{const body=await(await call(c,"/status",{})).json();assert.deepEqual(body,{connected:true,account_email:"ctiberius@gmail.com",scopes:[SCOPE],status:"active",live_access_verified:true});assert.equal(JSON.stringify(body).includes("never-expose"),false)}finally{globalThis.fetch=old}});
test("status distinguishes a stored grant from failed live access with allowlisted diagnostics",async()=>{const{coordinator:c,storage,env}=make();await storage.put("grant",await seal(env,{refresh_token:"never-expose-this",mailbox:"ctiberius@gmail.com",scope:SCOPE,status:"active"}));const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({error:"invalid_client",error_description:"must never escape"},{status:400});try{const body=await(await call(c,"/status",{})).json();assert.equal(body.connected,false);assert.equal(body.status,"stored_grant_unverified");assert.equal(body.live_access_verified,false);assert.equal(body.reason_code,"oauth_token_400:invalid_client");assert.equal(JSON.stringify(body).includes("description"),false);assert.equal(JSON.stringify(body).includes("never-expose"),false)}finally{globalThis.fetch=old}});
test("callback atomically consumes state and rejects replay",async()=>{const{coordinator:c,storage}=make(),b=await(await call(c,"/begin",{session_binding:"s"})).json(),state=new URL(b.authorization_url).searchParams.get("state"),nonce=(await storage.get(`flow:${state}`)).browser_nonce,old=globalThis.fetch;globalThis.fetch=async u=>String(u).includes("/profile")?Response.json({emailAddress:"ctiberius@gmail.com"}):Response.json({access_token:"a",refresh_token:"r",scope:SCOPE});try{assert.equal((await call(c,"/callback",{state,code:"c",browser_nonce:nonce,session_binding:"s"})).status,200);assert.equal((await call(c,"/callback",{state,code:"c",browser_nonce:nonce,session_binding:"s"})).status,400)}finally{globalThis.fetch=old}});
test("browser and initiating session bindings plus mailbox mismatch reject without a grant",async()=>{const{coordinator:c,storage}=make(),b=await(await call(c,"/begin",{session_binding:"s"})).json(),state=new URL(b.authorization_url).searchParams.get("state"),nonce=(await storage.get(`flow:${state}`)).browser_nonce;assert.equal((await call(c,"/callback",{state,code:"c",browser_nonce:"wrong",session_binding:"s"})).status,400);const b2=await(await call(c,"/begin",{session_binding:"s"})).json(),s2=new URL(b2.authorization_url).searchParams.get("state"),n2=(await storage.get(`flow:${s2}`)).browser_nonce;assert.equal((await call(c,"/callback",{state:s2,code:"c",browser_nonce:n2,session_binding:"wrong"})).status,400);const b3=await(await call(c,"/begin",{session_binding:"s"})).json(),s3=new URL(b3.authorization_url).searchParams.get("state"),n3=(await storage.get(`flow:${s3}`)).browser_nonce,old=globalThis.fetch;globalThis.fetch=async u=>String(u).includes("/profile")?Response.json({emailAddress:"other@example.com"}):Response.json({access_token:"a",refresh_token:"r",scope:SCOPE});try{assert.equal((await call(c,"/callback",{state:s3,code:"c",browser_nonce:n3,session_binding:"s"})).status,403);assert.equal(await storage.get("grant"),undefined)}finally{globalThis.fetch=old}});

test("initial token scope must be present and exactly gmail.readonly",async()=>{for(const scope of [undefined,`${SCOPE} https://www.googleapis.com/auth/gmail.modify`]){const{coordinator:c,storage}=make(),b=await(await call(c,"/begin",{session_binding:"s"})).json(),state=new URL(b.authorization_url).searchParams.get("state"),nonce=(await storage.get(`flow:${state}`)).browser_nonce,old=globalThis.fetch;globalThis.fetch=async()=>Response.json({access_token:"a",refresh_token:"r",scope});try{assert.equal((await call(c,"/callback",{state,code:"c",browser_nonce:nonce,session_binding:"s"})).status,403);assert.equal(await storage.get("grant"),undefined)}finally{globalThis.fetch=old}}});
test("refresh-token rotation persists and only invalid_grant marks revoked",async()=>{const{coordinator:c,storage,env}=make();await storage.put("grant",await seal(env,{refresh_token:"old",mailbox:"ctiberius@gmail.com",scope:SCOPE,status:"active"}));const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({access_token:"access",refresh_token:"new",expires_in:3600});try{assert.equal((await call(c,"/token",{})).status,200);assert.equal((await open(env,await storage.get("grant"))).refresh_token,"new");globalThis.fetch=async()=>Response.json({error:"temporarily_unavailable"},{status:400});assert.equal((await call(c,"/token",{})).status,400);assert.equal((await open(env,await storage.get("grant"))).status,"active");globalThis.fetch=async()=>Response.json({error:"invalid_grant"},{status:400});assert.equal((await call(c,"/token",{})).status,400);assert.equal((await open(env,await storage.get("grant"))).status,"revoked");assert.equal((await call(c,"/token",{})).status,409)}finally{globalThis.fetch=old}});

test("overlapping refresh is serialized and stale invalid_grant cannot revoke a newer grant",async()=>{const{coordinator:c,storage,env}=make();await storage.put("grant",await seal(env,{refresh_token:"old",mailbox:"ctiberius@gmail.com",scope:SCOPE,status:"active"}));let resolveFetch;const old=globalThis.fetch;globalThis.fetch=()=>new Promise(r=>{resolveFetch=r});try{const first=call(c,"/token",{});await new Promise(r=>setTimeout(r,0));assert.equal((await call(c,"/token",{})).status,409);resolveFetch(Response.json({access_token:"a",refresh_token:"rotated"}));assert.equal((await first).status,200);assert.equal((await open(env,await storage.get("grant"))).refresh_token,"rotated");const stale=call(c,"/token",{});await new Promise(r=>setTimeout(r,0));await storage.put("grant",await seal(env,{refresh_token:"newer",mailbox:"ctiberius@gmail.com",scope:SCOPE,status:"active"}));resolveFetch(Response.json({error:"invalid_grant"},{status:400}));assert.equal((await stale).status,400);const grant=await open(env,await storage.get("grant"));assert.equal(grant.refresh_token,"newer");assert.equal(grant.status,"active")}finally{globalThis.fetch=old}});

