export const CALLBACK_URL="https://true-north-citadel.ctiberius.workers.dev/oauth/google/callback",SCOPE="https://www.googleapis.com/auth/gmail.readonly",MAILBOX="ctiberius@gmail.com";
const te=new TextEncoder(),td=new TextDecoder(),b64=b=>btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const unb=s=>Uint8Array.from(atob(s.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((s.length+3)%4)),c=>c.charCodeAt(0)),random=n=>b64(crypto.getRandomValues(new Uint8Array(n))),json=(b,s=200)=>Response.json(b,{status:s,headers:{"cache-control":"no-store"}});
async function key(e){const r=unb(e.TOKEN_ENCRYPTION_KEY||"");if(r.length!==32)throw Error("invalid_token_encryption_key");return crypto.subtle.importKey("raw",r,"AES-GCM",false,["encrypt","decrypt"])}
export async function seal(e,v){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:"AES-GCM",iv},await key(e),te.encode(JSON.stringify(v)));return`${b64(iv)}.${b64(new Uint8Array(ct))}`}
export async function open(e,v){const[iv,ct]=String(v).split(".");if(!iv||!ct)throw Error("invalid_ciphertext");return JSON.parse(td.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:unb(iv)},await key(e),unb(ct))))}
async function challenge(v){return b64(new Uint8Array(await crypto.subtle.digest("SHA-256",te.encode(v))))}
async function postToken(e,p){const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:e.OAUTH_CLIENT_ID,client_secret:e.OAUTH_CLIENT_SECRET,...p})});if(!r.ok){const body=await r.json().catch(()=>({})),x=Error(`oauth_token_${r.status}`);x.status=r.status;x.oauth_error=body.error||null;throw x}return r.json()}
async function profile(t){const r=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/profile",{headers:{authorization:`Bearer ${t}`}});if(!r.ok)throw Error(`gmail_profile_${r.status}`);return r.json()}
function requiredBindings(e){if(!String(e.OAUTH_CLIENT_ID||"").endsWith(".apps.googleusercontent.com"))throw Error("oauth_client_id_missing");if(!e.OAUTH_CLIENT_SECRET)throw Error("oauth_client_secret_missing");if(!e.TOKEN_ENCRYPTION_KEY)throw Error("token_encryption_key_missing");if(!e.OAUTH_COORDINATOR)throw Error("oauth_coordinator_missing")}
function exactScope(value,{allowAbsent=false}={}){if(!value)return allowAbsent;const scopes=new Set(String(value).trim().split(/\s+/).filter(Boolean));return scopes.size===1&&scopes.has(SCOPE)}
export class OAuthCoordinator{constructor(state,env){this.state=state;this.env=env}async fetch(request){try{const u=new URL(request.url),b=request.method==="POST"?await request.json():{};
if(u.pathname==="/begin"){if(!b.session_binding)return json({error:"session_binding_required"},400);const state=random(32),browser_nonce=random(32),verifier=random(64),a=new URL("https://accounts.google.com/o/oauth2/v2/auth");await this.state.storage.put(`flow:${state}`,{session_binding:b.session_binding,browser_nonce,verifier,expires:Date.now()+600000});a.search=new URLSearchParams({client_id:this.env.OAUTH_CLIENT_ID,redirect_uri:CALLBACK_URL,response_type:"code",scope:SCOPE,access_type:"offline",prompt:"consent",include_granted_scopes:"false",state,code_challenge:await challenge(verifier),code_challenge_method:"S256"});return json({authorization_url:a.toString(),browser_nonce})}
if(u.pathname==="/callback"){let f;await this.state.storage.transaction(async tx=>{f=await tx.get(`flow:${b.state}`);if(f)await tx.delete(`flow:${b.state}`)});if(!f||f.expires<Date.now()||f.browser_nonce!==b.browser_nonce||f.session_binding!==b.session_binding)return json({error:"oauth_state_invalid"},400);const t=await postToken(this.env,{code:b.code,code_verifier:f.verifier,grant_type:"authorization_code",redirect_uri:CALLBACK_URL});if(!t.access_token||!t.refresh_token)return json({error:"oauth_missing_token"},400);if(!exactScope(t.scope))return json({error:"oauth_scope_invalid"},403);const p=await profile(t.access_token);if(String(p.emailAddress||"").toLowerCase()!==MAILBOX)return json({error:"mailbox_mismatch"},403);await this.state.storage.put("grant",await seal(this.env,{refresh_token:t.refresh_token,mailbox:MAILBOX,scope:SCOPE,status:"active",granted_at:Date.now()}));return json({connected:true,mailbox:MAILBOX})}
if(u.pathname==="/status"){const s=await this.state.storage.get("grant");if(!s)return json({connected:false,account_email:null,scopes:[],status:"disconnected",live_access_verified:false});const g=await open(this.env,s),stored=g.mailbox===MAILBOX&&g.scope===SCOPE&&g.status==="active";if(!stored)return json({connected:false,account_email:g.mailbox===MAILBOX?g.mailbox:null,scopes:g.scope===SCOPE?[SCOPE]:[],status:g.status==="revoked"?"revoked":"invalid",live_access_verified:false});const tokenResponse=await this.fetch(new Request("https://oauth-core.internal/token",{method:"POST",headers:{"content-type":"application/json"},body:"{}"}));if(!tokenResponse.ok){const failure=await tokenResponse.json().catch(()=>({}));return json({connected:false,account_email:MAILBOX,scopes:[SCOPE],status:"stored_grant_unverified",live_access_verified:false,reason_code:String(failure.error||"credential_refresh_failed").slice(0,80)})}const tokenBody=await tokenResponse.json(),p=await profile(tokenBody.access_token);if(String(p.emailAddress||"").toLowerCase()!==MAILBOX)return json({connected:false,account_email:null,scopes:[SCOPE],status:"mailbox_mismatch",live_access_verified:false});return json({connected:true,account_email:MAILBOX,scopes:[SCOPE],status:"active",live_access_verified:true})}
if(u.pathname==="/token"){const s=await this.state.storage.get("grant");if(!s)return json({error:"gmail_not_connected"},409);const g=await open(this.env,s);if(g.status!=="active"||g.mailbox!==MAILBOX||g.scope!==SCOPE)return json({error:"grant_invalid"},409);const lease=random(24);let acquired=false;await this.state.storage.transaction(async tx=>{const current=await tx.get("grant"),held=await tx.get("refresh_lease");if(current===s&&(!held||held.expires<Date.now())){await tx.put("refresh_lease",{id:lease,grant:s,expires:Date.now()+30000});acquired=true}});if(!acquired)return json({error:"refresh_in_progress"},409);try{const t=await postToken(this.env,{refresh_token:g.refresh_token,grant_type:"refresh_token"});if(!exactScope(t.scope,{allowAbsent:true})){await this.state.storage.transaction(async tx=>{const l=await tx.get("refresh_lease");if(l?.id===lease)await tx.delete("refresh_lease")});return json({error:"oauth_scope_invalid"},403)}let committed=false;await this.state.storage.transaction(async tx=>{const current=await tx.get("grant"),l=await tx.get("refresh_lease");if(current===s&&l?.id===lease){if(t.refresh_token){g.refresh_token=t.refresh_token;g.rotated_at=Date.now();await tx.put("grant",await seal(this.env,g))}await tx.delete("refresh_lease");committed=true}});if(!committed)return json({error:"refresh_superseded"},409);return json({access_token:t.access_token,expires_in:t.expires_in,token_type:t.token_type})}catch(e){await this.state.storage.transaction(async tx=>{const current=await tx.get("grant"),l=await tx.get("refresh_lease");if(l?.id!==lease)return;if(e.oauth_error==="invalid_grant"&&current===s){g.status="revoked";g.revoked_at=Date.now();await tx.put("grant",await seal(this.env,g))}await tx.delete("refresh_lease")});throw e}}
return json({error:"not_found"},404)}catch(e){const base=String(e.message||e).replace(/(token|secret|code)=[^&\s]+/gi,"$1=[redacted]"),detail=/^(?:invalid_client|invalid_grant|unauthorized_client|invalid_request)$/.test(String(e.oauth_error||""))?`:${e.oauth_error}`:"";return json({error:`${base}${detail}`},400)}}}
export default{async fetch(r,e){try{requiredBindings(e);const id=e.OAUTH_COORDINATOR.idFromName("primary");return e.OAUTH_COORDINATOR.get(id).fetch(r)}catch(error){return json({error:String(error.message||error)},503)}}};

