#!/usr/bin/env node
import {decodeNativeFrames,encodeNativeMessage} from "./framing.js";
import {validatePreparedSubmission} from "../shared/executor-core.js";
import {canonicalBodyHash} from "../shared/canonical-json.js";
import {canonicalDeviceProof} from "./device-proof.js";
import {createMacKeychainSigner} from "./macos-keychain-signer.js";
import {execFile as rawExecFile} from "node:child_process";import {promisify} from "node:util";
let pending=new Uint8Array();
function reply(value){process.stdout.write(Buffer.from(encodeNativeMessage(value)))}
const helper=process.env.TRUE_NORTH_KEYCHAIN_SIGNER_PATH,signer=helper?createMacKeychainSigner({execFile:async(path,args,input)=>promisify(rawExecFile)(path,args,{input}),helperPath:helper}):null;
function bytes(value){const base=String(value).replaceAll("-","+").replaceAll("_","/")+"=".repeat((4-String(value).length%4)%4);return Uint8Array.from(Buffer.from(base,"base64"))}
async function identity(create=false){if(!signer)return null;let public_key_spki_b64url;try{public_key_spki_b64url=create?await signer.create():await signer.publicKey()}catch{return null}const digest=await crypto.subtle.digest("SHA-256",bytes(public_key_spki_b64url)),public_key_fingerprint=Buffer.from(digest).toString("hex");return{device_id:`executor_device_${public_key_fingerprint.slice(0,32)}`,public_key_spki_b64url,public_key_fingerprint}}
async function handle(message){if(message?.type==="status"){const value=await identity(false);return{ok:true,protocol_version:1,paired:Boolean(value),device_id:value?.device_id||null,public_key_fingerprint:value?.public_key_fingerprint||null,installed_runtime:true,background_active:false}}if(message?.type==="create_key"){const value=await identity(true);return value?{ok:true,...value}:{ok:false,error:"key_creation_failed"}}if(message?.type==="public_key"){const value=await identity(false);return value?{ok:true,...value}:{ok:false,error:"key_not_found"}}if(message?.type==="revoke_key"){if(!signer)return{ok:false,error:"device_not_paired"};await signer.revoke();return{ok:true,revoked:true}}if(message?.type==="validate_prepared")try{return{ok:true,prepared:validatePreparedSubmission(message.prepared)}}catch{return{ok:false,error:"prepared_submission_invalid"}}if(message?.type==="sign_request"){const value=await identity(false);if(!value||message.device_id!==value.device_id)return{ok:false,error:"device_not_paired"};const fields={device_id:value.device_id,method:String(message.method||""),path:String(message.path||""),body_hash:await canonicalBodyHash(message.body),timestamp:new Date().toISOString(),nonce:crypto.randomUUID().replaceAll("-","")},signature=await signer(new TextEncoder().encode(canonicalDeviceProof(fields)));return{...fields,signature}}return{ok:false,error:"unsupported_native_message"}}
process.stdin.on("data",chunk=>{const joined=new Uint8Array(pending.byteLength+chunk.byteLength);joined.set(pending);joined.set(chunk,pending.byteLength);const decoded=decodeNativeFrames(joined);pending=decoded.remainder;for(const message of decoded.messages)handle(message).then(reply).catch(()=>reply({ok:false,error:"native_host_failure"}))});
process.stdin.on("end",()=>{if(pending.byteLength)process.exitCode=2});
