const HOST="company.justsignal.truenorth_executor",API="https://truenorth.justsignal.company";let pending=null,staged=null,executionContext=null;
function native(message){return new Promise((resolve,reject)=>chrome.runtime.sendNativeMessage(HOST,message,r=>chrome.runtime.lastError?reject(new Error("native_host_unavailable")):resolve(r)))}
function tabMessage(tabId,message){return new Promise((resolve,reject)=>chrome.tabs.sendMessage(tabId,message,r=>chrome.runtime.lastError||!r?.ok?reject(new Error(r?.error||"content_unavailable")):resolve(r.value)))}
async function post(path,body,proof,lease){const response=await fetch(API+path,{method:"POST",credentials:"include",headers:{"content-type":"application/json","x-executor-device-id":body.device_id||pending.device_id,"x-executor-timestamp":proof.timestamp,"x-executor-nonce":proof.nonce,"x-executor-signature":proof.signature,...(lease?{"x-application-lease":lease}:{})},body:JSON.stringify(body)});if(!response.ok)throw new Error("executor_api_rejected");return response.json()}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function waitForConfirmation(tabId,beforeUrl){for(let attempt=0;attempt<30;attempt++){await pause(500);try{await chrome.scripting.executeScript({target:{tabId},files:["content-script.js"]});const evidence=await tabMessage(tabId,{type:"TN_OBSERVE_SUBMISSION_CONFIRMATION",before_url:beforeUrl});if(evidence)return evidence}catch{}}throw new Error("trusted_confirmation_not_observed")}
async function revokeTemporaryOrigin(value){if(!value)return;try{await chrome.permissions.remove({origins:[value]})}catch{}}
function exactOriginPattern(value){const url=new URL(value);if(url.protocol!=="https:"||url.username||url.password||url.pathname!=="/"||url.search||url.hash)throw new Error("exact_origin_required");return url.origin+"/*"}
function validHandoff(value){try{return value?.kind==="true_north_browser_execution_handoff"&&String(value.queue_id).length>5&&new URL(value.destination_url).protocol==="https:"}catch{return false}}
chrome.runtime.onMessage.addListener((message,sender,reply)=>{if(sender.origin!==API&&!sender.url?.startsWith(API+"/"))return false;if(message?.type==="TN_GRANT_EXACT_ORIGIN"){let pattern;try{pattern=exactOriginPattern(message.origin)}catch{reply({ok:false,error:"exact_origin_required"});return false}chrome.permissions.request({origins:[pattern]}).then(granted=>reply(granted?{ok:true,origin_pattern:pattern}:{ok:false,error:"origin_permission_denied"}));return true}if(message?.type==="TN_STAGE_EXECUTION_HANDOFF"){if(!validHandoff(message.handoff)){reply({ok:false,error:"handoff_invalid"});return false}staged=structuredClone(message.handoff);reply({ok:true,status:"staged_waiting_for_local_extension_gesture"});return false}if(message?.type==="TN_QUEUE_EXACT_SUBMIT"){if(!executionContext||message.prepared?.queue_id!==executionContext.queue_id){reply({ok:false,error:"staged_handoff_required"});return false}pending={...message.prepared,lease_token:executionContext.lease_token};reply({ok:true,status:"waiting_for_local_extension_gesture"});return false}return false});
async function waitForTabComplete(tabId){for(let i=0;i<60;i++){const tab=await chrome.tabs.get(tabId);if(tab.status==="complete")return tab;await pause(250)}throw new Error("destination_load_timeout")}
async function prepareStagedHandoff(){const status=await native({type:"status"});if(!status?.paired||!status.device_id)throw new Error("device_not_paired");const created=await chrome.tabs.create({url:staged.destination_url,active:true}),tab=await waitForTabComplete(created.id);await chrome.scripting.executeScript({target:{tabId:tab.id},files:["content-script.js"]});const observed=await tabMessage(tab.id,{type:"TN_OBSERVE_FINAL_FORM"});if(new URL(observed.destination_url).hostname!==new URL(staged.destination_url).hostname)throw new Error("observed_binding_changed");const path=`/api/applications/${encodeURIComponent(staged.queue_id)}/claim`,body={device_id:status.device_id,lease_seconds:900},proof=await native({type:"sign_request",device_id:status.device_id,method:"POST",path,body}),claimed=await post(path,body,proof);executionContext={...staged,device_id:status.device_id,form_state_hash:observed.form_state_hash,lease_token:claimed.lease_token,tab_id:tab.id};staged=null;const authorize=new URL(API);authorize.searchParams.set("executor_authorize",executionContext.queue_id);authorize.searchParams.set("device_id",executionContext.device_id);authorize.searchParams.set("form_state_hash",executionContext.form_state_hash);await chrome.tabs.create({url:authorize.toString(),active:true})}
chrome.action.onClicked.addListener(async tab=>{if(!pending&&staged){try{await prepareStagedHandoff()}catch{staged=null}return}if(!pending||!tab?.id)return;const temporaryOrigin=pending.temporary_origin_grant,targetTab=executionContext?.tab_id||tab.id;try{await chrome.scripting.executeScript({target:{tabId:targetTab},files:["content-script.js"]});const observed=await tabMessage(targetTab,{type:"TN_OBSERVE_FINAL_FORM"});if(new URL(observed.destination_url).hostname!==new URL(pending.destination_url).hostname||observed.form_state_hash!==pending.form_state_hash)throw new Error("observed_binding_changed");const consumePath=`/api/applications/${encodeURIComponent(pending.queue_id)}/consume-final-submit`,consumeBody={authorization_id:pending.authorization_id,capability_token:pending.capability_token,device_id:pending.device_id,destination_url:observed.destination_url,form_state_hash:observed.form_state_hash},proof=await native({type:"sign_request",device_id:pending.device_id,method:"POST",path:consumePath,body:consumeBody}),consumed=await post(consumePath,consumeBody,proof,pending.lease_token);if(consumed.action!=="submit_once")throw new Error("consume_failed");const click=await tabMessage(targetTab,{type:"TN_SUBMIT_EXACT_ONCE",form_state_hash:observed.form_state_hash}),receipt=await waitForConfirmation(targetTab,click.before_url),receiptPath=`/api/applications/${encodeURIComponent(pending.queue_id)}/receipt`,receiptBody={...receipt,authorization_id:pending.authorization_id,device_id:pending.device_id},receiptProof=await native({type:"sign_request",device_id:pending.device_id,method:"POST",path:receiptPath,body:receiptBody});await post(receiptPath,receiptBody,receiptProof,pending.lease_token);pending=null;executionContext=null}catch{if(pending){const path=`/api/applications/${encodeURIComponent(pending.queue_id)}/uncertain`,body={device_id:pending.device_id,detail:"Submit was attempted but no trusted post-submit employer confirmation was observed; verify the employer site before retry."};try{const proof=await native({type:"sign_request",device_id:pending.device_id,method:"POST",path,body});await post(path,body,proof,pending.lease_token)}catch{}pending=null;executionContext=null}}finally{await revokeTemporaryOrigin(temporaryOrigin)}});
